// examples/frameworks/nuxt-app/pages/users/[id].vue
<template>
  <main>
    <h1>User {{ id }}</h1>
    <nav aria-label="Primary">
      <NuxtLink to="/">Home</NuxtLink>
    </nav>
    <p>Sample dynamic route expanded via routeDiscovery.samples.</p>
  </main>
</template>

<script setup lang="ts">
const route = useRoute();
const id = computed(() => String(route.params.id ?? "unknown"));
</script>

// examples/frameworks/next-app/app/products/[id]/page.tsx
import Link from "next/link";

export default function ProductPage({ params }: { params: { id: string } }) {
  return (
    <main>
      <h1>Product {params.id}</h1>
      <nav aria-label="Primary">
        <Link href="/">Home</Link>
      </nav>
      <p>Sample dynamic route expanded via routeDiscovery.samples.</p>
    </main>
  );
}
