// examples/frameworks/nuxt-app/pages/about.vue
<template>
  <main>
    <h1>About</h1>
    <nav aria-label="Primary">
      <NuxtLink to="/">Home</NuxtLink>
      ·
      <NuxtLink to="/about">About</NuxtLink>
    </nav>
    <p>This page intentionally includes a text input with no associated label.</p>
    <!-- AXE VIOLATION (label) -->
    <input type="text" name="message" />
  </main>
</template>

// examples/frameworks/next-app/app/about/page.tsx
import Link from "next/link";

export default function AboutPage() {
  return (
    <main>
      <h1>About</h1>
      <nav aria-label="Primary">
        <Link href="/">Home</Link>
        {" · "}
        <Link href="/about">About</Link>
      </nav>
      <p>This page intentionally includes a button with no accessible name.</p>
      {/* AXE VIOLATION (button-name) */}
      <button type="button"></button>
    </main>
  );
}
