// examples/frameworks/vue-vite/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from "vue-router";
</script>

<template>
  <div>
    <header>
      <h1>Framework Vue + Vite</h1>
      <nav aria-label="Primary">
        <RouterLink to="/">Home</RouterLink>
        |
        <RouterLink to="/issues">Issues</RouterLink>
      </nav>
    </header>
    <main>
      <RouterView />
    </main>
  </div>
</template>

// examples/frameworks/next-app/app/page.tsx
import Link from "next/link";

export default function HomePage() {
  return (
    <main>
      <h1>Framework Next.js example</h1>
      <nav aria-label="Primary">
        <Link href="/">Home</Link>
        {" · "}
        <Link href="/about">About</Link>
        {" · "}
        <Link href="/products/example">Example product</Link>
      </nav>
      <p>App Router routes are discovered from the filesystem.</p>
    </main>
  );
}
