// examples/frameworks/react-vite/src/App.tsx
import { Link, Route, Routes } from "react-router-dom";
import { HomePage } from "./pages/HomePage";
import { IssuesPage } from "./pages/IssuesPage";

export function App() {
  return (
    <div>
      <header>
        <h1>Framework React + Vite</h1>
        <nav aria-label="Primary">
          <Link to="/">Home</Link>
          {" | "}
          <Link to="/issues">Issues</Link>
        </nav>
      </header>
      <main>
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/issues" element={<IssuesPage />} />
        </Routes>
      </main>
    </div>
  );
}

// examples/frameworks/vue-vite/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from "vue-router";
</script>

<template>
  <div>
    <header>
      <h1>Framework Vue + Vite</h1>
      <nav aria-label="Primary">
        <RouterLink to="/">Home</RouterLink>
        |
        <RouterLink to="/issues">Issues</RouterLink>
      </nav>
    </header>
    <main>
      <RouterView />
    </main>
  </div>
</template>
