// examples/frameworks/angular-app/src/app/app.component.ts
import { Component } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [RouterLink, RouterOutlet],
  template: `
    <header>
      <h1>Framework Angular</h1>
      <nav aria-label="Primary">
        <a routerLink="/">Home</a>
        |
        <a routerLink="/contact">Contact</a>
      </nav>
    </header>
    <main>
      <router-outlet />
    </main>
  `,
})
export class AppComponent {}

// examples/frameworks/vue-vite/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from "vue-router";
</script>

<template>
  <div>
    <header>
      <h1>Framework Vue + Vite</h1>
      <nav aria-label="Primary">
        <RouterLink to="/">Home</RouterLink>
        |
        <RouterLink to="/issues">Issues</RouterLink>
      </nav>
    </header>
    <main>
      <RouterView />
    </main>
  </div>
</template>
